-- ============================================================================
-- SILVER LAYER — validation, quarantine, and cleaning
-- Run in RBNA_CASE_STUDY database. Creates SILVER schema objects from RAW.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS RBNA_CASE_STUDY.SILVER;
USE SCHEMA RBNA_CASE_STUDY.SILVER;

-- ----------------------------------------------------------------------------
-- 1. OUTLET — grain: ID_EXT_LINK
--    Root-cause validation: malformed source quoting occasionally shifts
--    column values in a row. Since ID_EXT_LINK and ID_OUTLET are expected
--    to be large numeric IDs, TRY_TO_DECIMAL cleanly flags shifted rows —
--    same check used across all 3 raw tables since it's one root cause.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TABLE SILVER.OUTLET_QUARANTINE AS
SELECT *
FROM RAW.OUTLET
WHERE TRY_TO_DECIMAL(ID_EXT_LINK) IS NULL
   OR TRY_TO_DECIMAL(ID_OUTLET) IS NULL;

CREATE OR REPLACE TABLE SILVER.OUTLET AS
SELECT
    ID_EXT_LINK::NUMBER          AS ID_EXT_LINK,
    ID_OUTLET::NUMBER            AS ID_OUTLET,
    TRY_TO_NUMBER(ID_PLATFORM)   AS ID_PLATFORM,
    PLATFORM_NAME,
    NAME,
    CATEGORY,
    CUISINE,
    MARKET,
    STREET_ADDRESS,
    POSTAL_CODE,
    ADDRESS_LOCALITY,
    ADDRESS_COUNTRY,
    TRY_TO_DOUBLE(LATITUDE)      AS LATITUDE,
    TRY_TO_DOUBLE(LONGITUDE)     AS LONGITUDE,
    TRY_TO_NUMBER(NUM_RATINGS)   AS NUM_RATINGS,
    TRY_TO_DOUBLE(AVERAGE_RATING) AS AVERAGE_RATING,
    TRY_TO_DOUBLE(AVERAGE_COST)  AS AVERAGE_COST,
    TRY_TO_DOUBLE(MIN_ORDER_AMOUNT) AS MIN_ORDER_AMOUNT,
    LOCAL_CURRENCY,
    UPPER(GHOST_KITCHEN)         AS GHOST_KITCHEN,
    TRY_TO_DATE(CREATED_AT)      AS CREATED_AT,
    SEGMENT_TYPE,
    _SOURCE_MARKET,
    _SOURCE_FILE_NAME,
    _LOADED_AT
FROM RAW.OUTLET
WHERE TRY_TO_DECIMAL(ID_EXT_LINK) IS NOT NULL
  AND TRY_TO_DECIMAL(ID_OUTLET) IS NOT NULL
-- de-dup: keep one row per ID_EXT_LINK (the ~2 exact duplicates found earlier)
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID_EXT_LINK ORDER BY _LOADED_AT DESC) = 1;

-- ----------------------------------------------------------------------------
-- 2. MATCHING — grain: ID_EXT_LINK
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TABLE SILVER.MATCHING_QUARANTINE AS
SELECT *
FROM RAW.MATCHING
WHERE TRY_TO_DECIMAL(ID_EXT_LINK) IS NULL
   OR TRY_TO_DECIMAL(ID_OUTLET) IS NULL;

CREATE OR REPLACE TABLE SILVER.MATCHING AS
SELECT
    ID_EXT_LINK::NUMBER           AS ID_EXT_LINK,
    ID_OUTLET::NUMBER             AS ID_OUTLET,
    TRY_TO_NUMBER(ID_PLATFORM)    AS ID_PLATFORM,
    PLATFORM_NAME,
    TRY_TO_DOUBLE(SIMILARITY_SCORE_NAME)    AS SIMILARITY_SCORE_NAME,
    TRY_TO_DOUBLE(SIMILARITY_SCORE_ADDRESS) AS SIMILARITY_SCORE_ADDRESS,
    MERGED_CHAIN_NAME,
    TRY_TO_BOOLEAN(IS_CHAIN)      AS IS_CHAIN,
    TRY_TO_NUMBER(NUM_RESTAURANTS) AS NUM_RESTAURANTS,
    TRY_TO_BOOLEAN(SERVES_DRINKS)  AS SERVES_DRINKS,
    TRY_TO_BOOLEAN(SERVES_RED_BULL) AS SERVES_RED_BULL,
    TRY_TO_BOOLEAN(SUGAR_FREE_AVAILABLE) AS SUGAR_FREE_AVAILABLE,
    TRY_TO_BOOLEAN(ORGANICS_AVAILABLE)   AS ORGANICS_AVAILABLE,
    TRY_TO_BOOLEAN(EDITIONS_AVAILABLE)   AS EDITIONS_AVAILABLE,
    TRY_TO_NUMBER(LEADING_ID_EXT_LINK) AS LEADING_ID_EXT_LINK,  -- semantics unconfirmed, kept as-is (see data quality notes)
    TRY_TO_DATE(CREATED_AT)       AS CREATED_AT
FROM RAW.MATCHING
WHERE TRY_TO_DECIMAL(ID_EXT_LINK) IS NOT NULL
  AND TRY_TO_DECIMAL(ID_OUTLET) IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID_EXT_LINK ORDER BY SIMILARITY_SCORE_ADDRESS DESC) = 1;

-- ----------------------------------------------------------------------------
-- 3. PORTFOLIO — grain: (ID_EXT_LINK, ID_BEVERAGE) — confirmed unique
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TABLE SILVER.PORTFOLIO_QUARANTINE AS
SELECT *
FROM RAW.PORTFOLIO
WHERE TRY_TO_DECIMAL(ID_BEVERAGE) IS NULL
   OR TRY_TO_DECIMAL(ID_EXT_LINK) IS NULL;

CREATE OR REPLACE TABLE SILVER.PORTFOLIO AS
SELECT
    ID_BEVERAGE::NUMBER         AS ID_BEVERAGE,
    ID_EXT_LINK::NUMBER         AS ID_EXT_LINK,
    TRY_TO_NUMBER(ID_OUTLET)    AS ID_OUTLET,
    ITEM_POSITION,
    ITEM_CATEGORY,               -- keep raw messy text too; category cleanup happens in Gold
    TRY_TO_NUMBER(ID_DRINK)      AS ID_DRINK,
    ITEM_MANUFACTURER,
    ITEM_BRAND,
    ITEM_SUBBRAND,
    TRY_TO_DOUBLE(ITEM_VOLUME)  AS ITEM_VOLUME,
    TRY_TO_DOUBLE(ITEM_PRICE)   AS ITEM_PRICE,
    ITEM_DRINK_CATEGORY_1,
    ITEM_DRINK_CATEGORY_2,
    ITEM_NAME,
    ITEM_DESC,
    CREATED_AT,
    _SOURCE_MARKET,
    _SOURCE_FILE_NAME,
    _LOADED_AT
FROM RAW.PORTFOLIO
WHERE TRY_TO_DECIMAL(ID_BEVERAGE) IS NOT NULL
  AND TRY_TO_DECIMAL(ID_EXT_LINK) IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID_EXT_LINK, ID_BEVERAGE ORDER BY _LOADED_AT DESC) = 1;

-- ----------------------------------------------------------------------------
-- Quick sanity checks — run after building the above
-- ----------------------------------------------------------------------------
SELECT 'OUTLET' AS tbl, COUNT(*) AS clean_rows FROM SILVER.OUTLET
UNION ALL
SELECT 'OUTLET_QUARANTINE', COUNT(*) FROM SILVER.OUTLET_QUARANTINE
UNION ALL
SELECT 'MATCHING', COUNT(*) FROM SILVER.MATCHING
UNION ALL
SELECT 'MATCHING_QUARANTINE', COUNT(*) FROM SILVER.MATCHING_QUARANTINE
UNION ALL
SELECT 'PORTFOLIO', COUNT(*) FROM SILVER.PORTFOLIO
UNION ALL
SELECT 'PORTFOLIO_QUARANTINE', COUNT(*) FROM SILVER.PORTFOLIO_QUARANTINE;